# Generated by Django 5.0.2 on 2024-02-19 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liste',
            name='description',
        ),
    ]
