# Generated by Django 5.0.2 on 2024-02-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_App', '0003_remove_tache_liste_liste_taches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liste',
            name='taches',
        ),
        migrations.AddField(
            model_name='tache',
            name='listes',
            field=models.ManyToManyField(related_name='taches', to='Todo_App.liste'),
        ),
    ]
