# Generated by Django 5.0.2 on 2024-02-20 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_App', '0004_remove_liste_taches_tache_listes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='fk_liste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Todo_App.liste'),
        ),
    ]
