# Generated by Django 5.0.2 on 2024-02-25 14:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_App', '0005_tache_fk_liste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tache',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='tache',
            name='fk_liste',
        ),
        migrations.RemoveField(
            model_name='tache',
            name='listes',
        ),
        migrations.AddField(
            model_name='tache',
            name='liste',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='Todo_App.liste'),
            preserve_default=False,
        ),
    ]
